version: 2

sources:
  - name: landing
    database: dbt_sd_sandbox
    schema: l1_landing
    tables:
      - name: customers
        columns:
          - name: customer_id
            data_tests:
              - unique
              - not_null
      - name: orders
      - name: dates
      - name: employees
      - name: order_items
      - name: products
      - name: stores
      - name: suppliers